name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo 'Building the site...'
          npm install
          npm run build

      - name: Deploy
        run: |
          echo 'Deploying the site...'
          # Ajoutez ici vos commandes de déploiement
          echo 'Déploiement en cours...'
          # Exemple de déploiement à GitHub Pages
          npm run deploy
