name: Deploy to WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync files to WordPress
        run: |
          # Installez wp-cli
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

          # Configurez les variables d'environnement pour WordPress
          WP_URL="https://davidkrk.wordpress.com"
          WP_USER="${{ secrets.WP_USER }}"
          WP_PASS="${{ secrets.WP_PASS }}"
          
          # Déployer les fichiers vers WordPress
          for file in $(find . -type f); do
            wp media import $file --path=$WP_URL --user=$WP_USER --prompt=$WP_PASS
          done
