name: Lighthouse
on:
  pull_request:
    branches: [ gh-pages ]
  workflow_dispatch:   # <-- Ajoutez cette ligne

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: treosh/lighthouse-ci-action@v9
      with:
        urls: https://davidkrk.github.io/
